.TH fasih 1 2011-01-05 fasih(1) "User's Manual"
.SH NAME
fasih - Fasih Ahmad Fakhri
.SH SYNOPSIS
fasih [--developer]
.SH SUMMARY
crypto anarchist, free software activist, mathematician, programmer, pythonista
.SH DESCRIPTION
fasih uses GPG to easily secure communications with a robust encryption method.
.nf
.B $ 
.I gpg --fingerprint 0x5A0CEB9A
pub   rsa2048 2011-12-27 [SC]                                                   
      4AFB 37C8 F52A 41C9 F3C8  A91B 5932 6239 5A0C EB9A                        
uid           Fasih Ahmad Fakhri &lt;fasih@email.com&gt;                        
sub   rsa2048 2011-12-27 [E]                                                    
.B $
.SH OTHER OPTIONS
.nf
- 050fe14bafefcc65b92c6d59d909742b1a5c245f97d99b55a8c37e958924e2502b
.SH SEE ALSO
fasih(4), fasih(7), fasih(8)
